# Generated by Django 2.2 on 2019-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description there is nothing in the area to eat. Where should I go to get some curry chicken blah blah blah there is more of the same to come just let  me think of another way to make this more long.'),
            preserve_default=False,
        ),
    ]
