# Generated by Django 2.2 on 2019-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
